### ISSUE TITLE
KeyError: 'items'

### ISSUE THREAD

**Issue by juniorkalvin7** [tcoimbra/getSophosCentralData#1]
I am accepting the following error

  File "/opt/monitoring/sophosCentralV2/getSophosCentralData.py", line 127, in <module>
    for item in alerts["items"]:
KeyError: 'items'

**Comment by Tronier447** [comment]
Have the same problem

**Comment by tcoimbra** [comment]
Hello,

Maybe there is an issue with the data returned by Sophos Central. In the Sophos API documentation (https://developer.sophos.com/docs/common-v1/1/routes/alerts/get), the Items are always provided.

Nevertheless, I updated the code to have better error management. Please give it a try.

**Comment by Tronier447** [comment]
HTTP Error during token request: 400 Client Error: BAD REQUEST for url: https://id.sophos.com/api/v2/oauth2/token
HTTP Error: 401 Client Error: Unauthorized for url: https://api.central.sophos.com/whoami/v1
Traceback (most recent call last):
  File "/home/getSophosCentralData/getSophosCentralData.py", line 163, in <module>
    alerts = get_Alerts()
  File "/home/getSophosCentralData/getSophosCentralData.py", line 99, in get_Alerts
    headers[organization_header] = organization_id
TypeError: 'NoneType' object does not support item assignment


That is my Error

**Comment by Tronier447** [comment]
Error fetching alerts: HTTP 400
Response: {
    "error": "badRequest",
    "correlationId": "***",
    "requestId": "***",
    "message": "Required request header 'X-Tenant-ID' for method parameter type UUID is not present"
}
Traceback (most recent call last):
  File "/home/getSophosCentralData/getSophosCentralData.py", line 169, in <module>
    for item in alerts["items"]:
KeyError: 'items'

**Comment by juniorkalvin7** [comment]
Error fetching alerts: HTTP 400
Response: {
    "error": "badRequest",
    "correlationId": "XXXXXX-XXXX-XXXXXX-XXXXXX",
    "requestId": "XXXXXXX-XXXXX-XXXXXXX-XXXXXX-XXXXXXXXXX",
    "message": "Required request header 'X-Tenant-ID' for method parameter type UUID is not present"
}
Traceback (most recent call last):
  File "/opt/monitoring/sophosCentralV2/getSophosCentralData.py", line 169, in <module>
    for item in alerts["items"]:
KeyError: 'items'

**Comment by tcoimbra** [comment]
Do your accounts have access to multiple tenants? Mine only have one. This script is meant to get data for 1 tenant only. Should I modify the script to specify a precise tenant ?

**Comment by Tronier447** [comment]
Hey, would there also be a way to convert this to multitenant?
